-- СВЕДЕНИЯ О СОСТАВЕ ИНФОРМАЦИИ ФЕДЕРАЛЬНОЙ ИНФОРМАЦИОННОЙ АДРЕСНОЙ СИСТЕМЫ 
-- Приложение 3
-- Код субъектов Российской Федерации (регионов)

INSERT INTO region(code, name) VALUES('01', 'Республика Адыгея (Адыгея)');
INSERT INTO region(code, name) VALUES('02', 'Республика Башкортостан');
INSERT INTO region(code, name) VALUES('03', 'Республика Бурятия');
INSERT INTO region(code, name) VALUES('04', 'Республика Алтай');
INSERT INTO region(code, name) VALUES('05', 'Республика Дагестан');
INSERT INTO region(code, name) VALUES('06', 'Республика Ингушетия');
INSERT INTO region(code, name) VALUES('07', 'Кабардино-Балкарская Республика');
INSERT INTO region(code, name) VALUES('08', 'Республика Калмыкия');
INSERT INTO region(code, name) VALUES('09', 'Карачаево-Черкесская Республика');
INSERT INTO region(code, name) VALUES('10', 'Республика Карелия');
INSERT INTO region(code, name) VALUES('11', 'Республика Коми');
INSERT INTO region(code, name) VALUES('12', 'Республика Марий Эл');
INSERT INTO region(code, name) VALUES('13', 'Республика Мордовия');
INSERT INTO region(code, name) VALUES('14', 'Республика Саха (Якутия)');
INSERT INTO region(code, name) VALUES('15', 'Республика Северная Осетия - Алания');
INSERT INTO region(code, name) VALUES('16', 'Республика Татарстан (Татарстан)');
INSERT INTO region(code, name) VALUES('17', 'Республика Тыва');
INSERT INTO region(code, name) VALUES('18', 'Удмуртская Республика');
INSERT INTO region(code, name) VALUES('19', 'Республика Хакасия');
INSERT INTO region(code, name) VALUES('20', 'Чеченская Республика');
INSERT INTO region(code, name) VALUES('21', 'Чувашская Республика - Чувашия');
INSERT INTO region(code, name) VALUES('22', 'Алтайский край');
INSERT INTO region(code, name) VALUES('23', 'Краснодарский край');
INSERT INTO region(code, name) VALUES('24', 'Красноярский край');
INSERT INTO region(code, name) VALUES('25', 'Приморский край');
INSERT INTO region(code, name) VALUES('26', 'Ставропольский край');
INSERT INTO region(code, name) VALUES('27', 'Хабаровский край');
INSERT INTO region(code, name) VALUES('28', 'Амурская область');
INSERT INTO region(code, name) VALUES('29', 'Архангельская область');
INSERT INTO region(code, name) VALUES('30', 'Астраханская область');
INSERT INTO region(code, name) VALUES('31', 'Белгородская область');
INSERT INTO region(code, name) VALUES('32', 'Брянская область');
INSERT INTO region(code, name) VALUES('33', 'Владимирская область');
INSERT INTO region(code, name) VALUES('34', 'Волгоградская область');
INSERT INTO region(code, name) VALUES('35', 'Вологодская область');
INSERT INTO region(code, name) VALUES('36', 'Воронежская область');
INSERT INTO region(code, name) VALUES('37', 'Ивановская область');
INSERT INTO region(code, name) VALUES('38', 'Иркутская область');
INSERT INTO region(code, name) VALUES('39', 'Калининградская область');
INSERT INTO region(code, name) VALUES('40', 'Калужская область');
INSERT INTO region(code, name) VALUES('41', 'Камчатский край');
INSERT INTO region(code, name) VALUES('42', 'Кемеровская область');
INSERT INTO region(code, name) VALUES('43', 'Кировская область');
INSERT INTO region(code, name) VALUES('44', 'Костромская область');
INSERT INTO region(code, name) VALUES('45', 'Курганская область');
INSERT INTO region(code, name) VALUES('46', 'Курская область');
INSERT INTO region(code, name) VALUES('47', 'Ленинградская область');
INSERT INTO region(code, name) VALUES('48', 'Липецкая область');
INSERT INTO region(code, name) VALUES('49', 'Магаданская область');
INSERT INTO region(code, name) VALUES('50', 'Московская область');
INSERT INTO region(code, name) VALUES('51', 'Мурманская область');
INSERT INTO region(code, name) VALUES('52', 'Нижегородская область');
INSERT INTO region(code, name) VALUES('53', 'Новгородская область');
INSERT INTO region(code, name) VALUES('54', 'Новосибирская область');
INSERT INTO region(code, name) VALUES('55', 'Омская область');
INSERT INTO region(code, name) VALUES('56', 'Оренбургская область');
INSERT INTO region(code, name) VALUES('57', 'Орловская область');
INSERT INTO region(code, name) VALUES('58', 'Пензенская область');
INSERT INTO region(code, name) VALUES('59', 'Пермский край');
INSERT INTO region(code, name) VALUES('60', 'Псковская область');
INSERT INTO region(code, name) VALUES('61', 'Ростовская область');
INSERT INTO region(code, name) VALUES('62', 'Рязанская область');
INSERT INTO region(code, name) VALUES('63', 'Самарская область');
INSERT INTO region(code, name) VALUES('64', 'Саратовская область');
INSERT INTO region(code, name) VALUES('65', 'Сахалинская область');
INSERT INTO region(code, name) VALUES('66', 'Свердловская область');
INSERT INTO region(code, name) VALUES('67', 'Смоленская область');
INSERT INTO region(code, name) VALUES('68', 'Тамбовская область');
INSERT INTO region(code, name) VALUES('69', 'Тверская область');
INSERT INTO region(code, name) VALUES('70', 'Томская область');
INSERT INTO region(code, name) VALUES('71', 'Тульская область');
INSERT INTO region(code, name) VALUES('72', 'Тюменская область');
INSERT INTO region(code, name) VALUES('73', 'Ульяновская область');
INSERT INTO region(code, name) VALUES('74', 'Челябинская область');
INSERT INTO region(code, name) VALUES('75', 'Забайкальский край');
INSERT INTO region(code, name) VALUES('76', 'Ярославская область');
INSERT INTO region(code, name) VALUES('77', 'Г.Москва');
INSERT INTO region(code, name) VALUES('78', 'Г.Санкт-Петербург');
INSERT INTO region(code, name) VALUES('79', 'Еврейская автономная область');
INSERT INTO region(code, name) VALUES('83', 'Ненецкий автономный округ');
INSERT INTO region(code, name) VALUES('86', 'Ханты-Мансийский автономный округ - Югра');
INSERT INTO region(code, name) VALUES('87', 'Чукотский автономный округ');
INSERT INTO region(code, name) VALUES('89', 'Ямало-Ненецкий автономный округ');
INSERT INTO region(code, name) VALUES('99', 'Иные территории, включая город и космодром Байконур');